default_config = {
            "search_queries": [
                "cat:cs.CV",
                "llava",
                "llava-med"
            ],
            "max_results": 5,
            "download_path": "./arxiv_papers",
            "check_interval_hours": 6,
            "last_check": None,  # 保留用于兼容性
            "query_last_check": {},  # 新增：每个查询的最后检查时间
            "downloaded_papers": [],
            "first_run": True,
            "organize_by_query": True  # 是否按搜索词组织文件夹
        }


# 预定义的查询映射
query_mapping = {
            "cat:cs.AI": "01_人工智能_AI",
            "cat:cs.LG": "02_机器学习_ML", 
            "cat:cs.CV": "03_计算机视觉_CV",
            "cat:cs.CL": "04_自然语言处理_NLP",
            "cat:cs.RO": "05_机器人学_Robotics",
            "cat:cs.NE": "06_神经网络_Neural",
            "cat:stat.ML": "07_统计机器学习_StatML",
            "cat:cs.CR": "08_密码学_Crypto",
            "cat:cs.DC": "09_分布式计算_Distributed",
            "cat:cs.IR": "10_信息检索_IR",
            "cat:cs.SI": "11_社会信息学_Social",
            "cat:cs.HC": "12_人机交互_HCI",
            "cat:cs.GT": "13_游戏理论_GameTheory",
            "cat:cs.CC": "14_计算复杂性_Complexity",
            "cat:cs.DS": "15_数据结构算法_DS",
            "cat:cs.DB": "16_数据库_Database",
            "cat:cs.SE": "17_软件工程_SE",
            "cat:cs.PL": "18_编程语言_PL",
            "cat:cs.OS": "19_操作系统_OS",
            "cat:cs.NI": "20_网络_Networking",
            "cat:cs.SY": "21_系统控制_Systems",
            "cat:cs.ET": "22_新兴技术_EmergingTech",
            "cat:cs.MA": "23_多智能体_MultiAgent",
            "cat:cs.MM": "24_多媒体_Multimedia",
            "cat:cs.SD": "25_音频处理_SoundAudio",
            "cat:cs.GR": "26_图形学_Graphics",
            "cat:cs.CG": "27_计算几何_CompGeometry",
            "cat:cs.NA": "28_数值分析_NumericalAnalysis",
            "cat:cs.SC": "29_符号计算_SymbolicComp",
            "cat:cs.DM": "30_离散数学_DiscreteMath",
            "cat:cs.FL": "31_形式语言_FormalLang",
            "cat:cs.LO": "32_逻辑_Logic",
            "cat:cs.CY": "33_计算机教育_Education",
            "cat:cs.OH": "34_其他_Other",
            "deep learning": "关键词_深度学习_DeepLearning",
            "neural network": "关键词_神经网络_NeuralNetwork", 
            "transformer": "关键词_Transformer",
            "large language model": "关键词_大语言模型_LLM",
            "diffusion model": "关键词_扩散模型_Diffusion",
            "reinforcement learning": "关键词_强化学习_RL",
            "computer vision": "关键词_计算机视觉_CV",
            "natural language processing": "关键词_自然语言处理_NLP",
            "machine learning": "关键词_机器学习_ML",
            "artificial intelligence": "关键词_人工智能_AI",
            "robotics": "关键词_机器人_Robotics",
            "autonomous": "关键词_自主系统_Autonomous",
            "gan": "关键词_生成对抗网络_GAN",
            "vae": "关键词_变分自编码器_VAE",
            "bert": "关键词_BERT",
            "gpt": "关键词_GPT",
            "attention": "关键词_注意力机制_Attention",
            "federated learning": "关键词_联邦学习_FederatedLearning",
            "transfer learning": "关键词_迁移学习_TransferLearning",
            "meta learning": "关键词_元学习_MetaLearning",
            "few shot": "关键词_少样本学习_FewShot",
            "zero shot": "关键词_零样本学习_ZeroShot",
            "self supervised": "关键词_自监督学习_SelfSupervised",
            "unsupervised": "关键词_无监督学习_Unsupervised",
            "supervised": "关键词_监督学习_Supervised",
            "semi supervised": "关键词_半监督学习_SemiSupervised",
            "graph neural": "关键词_图神经网络_GNN",
            "recommendation": "关键词_推荐系统_RecSys",
            "optimization": "关键词_优化_Optimization",
            "quantum": "关键词_量子计算_Quantum",
            "blockchain": "关键词_区块链_Blockchain",
            "edge computing": "关键词_边缘计算_EdgeComputing",
            "explainable": "关键词_可解释AI_ExplainableAI",
            "fairness": "关键词_公平性_Fairness",
            "privacy": "关键词_隐私保护_Privacy",
            "adversarial": "关键词_对抗样本_Adversarial",
            "continual learning": "关键词_持续学习_ContinualLearning",
            "multimodal": "关键词_多模态_Multimodal",
            "time series": "关键词_时间序列_TimeSeries",
            "causality": "关键词_因果推理_Causality",
            "bayesian": "关键词_贝叶斯_Bayesian"
        }

categories = {
            "计算机科学 (Computer Science)": {
                "cat:cs.AI": "人工智能 (Artificial Intelligence)",
                "cat:cs.AR": "硬件架构 (Hardware Architecture)", 
                "cat:cs.CC": "计算复杂性 (Computational Complexity)",
                "cat:cs.CE": "计算工程 (Computational Engineering)",
                "cat:cs.CG": "计算几何 (Computational Geometry)",
                "cat:cs.CL": "计算与语言 (Computation and Language)",
                "cat:cs.CR": "密码学与安全 (Cryptography and Security)",
                "cat:cs.CV": "计算机视觉 (Computer Vision and Pattern Recognition)",
                "cat:cs.CY": "计算机与社会 (Computers and Society)",
                "cat:cs.DB": "数据库 (Databases)",
                "cat:cs.DC": "分布式计算 (Distributed, Parallel, and Cluster Computing)",
                "cat:cs.DL": "数字图书馆 (Digital Libraries)",
                "cat:cs.DM": "离散数学 (Discrete Mathematics)",
                "cat:cs.DS": "数据结构与算法 (Data Structures and Algorithms)",
                "cat:cs.ET": "新兴技术 (Emerging Technologies)",
                "cat:cs.FL": "形式语言 (Formal Languages and Automata Theory)",
                "cat:cs.GL": "通用文献 (General Literature)",
                "cat:cs.GR": "图形学 (Graphics)",
                "cat:cs.GT": "计算机科学与博弈论 (Computer Science and Game Theory)",
                "cat:cs.HC": "人机交互 (Human-Computer Interaction)",
                "cat:cs.IR": "信息检索 (Information Retrieval)",
                "cat:cs.IT": "信息论 (Information Theory)",
                "cat:cs.LG": "机器学习 (Machine Learning)",
                "cat:cs.LO": "逻辑 (Logic in Computer Science)",
                "cat:cs.MA": "多智能体系统 (Multiagent Systems)",
                "cat:cs.MM": "多媒体 (Multimedia)",
                "cat:cs.MS": "数学软件 (Mathematical Software)",
                "cat:cs.NA": "数值分析 (Numerical Analysis)",
                "cat:cs.NE": "神经网络 (Neural and Evolutionary Computing)",
                "cat:cs.NI": "网络 (Networking and Internet Architecture)",
                "cat:cs.OH": "其他计算机科学 (Other Computer Science)",
                "cat:cs.OS": "操作系统 (Operating Systems)",
                "cat:cs.PF": "性能 (Performance)",
                "cat:cs.PL": "编程语言 (Programming Languages)",
                "cat:cs.RO": "机器人学 (Robotics)",
                "cat:cs.SC": "符号计算 (Symbolic Computation)",
                "cat:cs.SD": "音频 (Sound)",
                "cat:cs.SE": "软件工程 (Software Engineering)",
                "cat:cs.SI": "社会信息网络 (Social and Information Networks)",
                "cat:cs.SY": "系统与控制 (Systems and Control)"
            },
            "统计学 (Statistics)": {
                "cat:stat.AP": "应用统计 (Applications)",
                "cat:stat.CO": "计算统计 (Computation)",
                "cat:stat.ME": "方法论 (Methodology)",
                "cat:stat.ML": "机器学习 (Machine Learning)",
                "cat:stat.OT": "其他统计 (Other Statistics)",
                "cat:stat.TH": "统计理论 (Statistics Theory)"
            },
            "数学 (Mathematics)": {
                "cat:math.AG": "代数几何 (Algebraic Geometry)",
                "cat:math.AT": "代数拓扑 (Algebraic Topology)",
                "cat:math.AP": "分析与偏微分方程 (Analysis of PDEs)",
                "cat:math.CT": "范畴论 (Category Theory)",
                "cat:math.CA": "经典分析与常微分方程 (Classical Analysis and ODEs)",
                "cat:math.CO": "组合数学 (Combinatorics)",
                "cat:math.AC": "交换代数 (Commutative Algebra)",
                "cat:math.CV": "复变量 (Complex Variables)",
                "cat:math.DG": "微分几何 (Differential Geometry)",
                "cat:math.DS": "动力系统 (Dynamical Systems)",
                "cat:math.FA": "泛函分析 (Functional Analysis)",
                "cat:math.GM": "通用数学 (General Mathematics)",
                "cat:math.GN": "一般拓扑 (General Topology)",
                "cat:math.GT": "几何拓扑 (Geometric Topology)",
                "cat:math.GR": "群论 (Group Theory)",
                "cat:math.HO": "数学史 (History and Overview)",
                "cat:math.IT": "信息论 (Information Theory)",
                "cat:math.KT": "K理论 (K-Theory and Homology)",
                "cat:math.LO": "逻辑 (Logic)",
                "cat:math.MP": "数学物理 (Mathematical Physics)",
                "cat:math.MG": "度量几何 (Metric Geometry)",
                "cat:math.NT": "数论 (Number Theory)",
                "cat:math.NA": "数值分析 (Numerical Analysis)",
                "cat:math.OA": "算子代数 (Operator Algebras)",
                "cat:math.OC": "优化与控制 (Optimization and Control)",
                "cat:math.PR": "概率论 (Probability)",
                "cat:math.QA": "量子代数 (Quantum Algebra)",
                "cat:math.RT": "表示论 (Representation Theory)",
                "cat:math.RA": "环与代数 (Rings and Algebras)",
                "cat:math.SP": "谱理论 (Spectral Theory)",
                "cat:math.ST": "统计理论 (Statistics Theory)",
                "cat:math.SG": "辛几何 (Symplectic Geometry)"
            }
        }